- name: copy config file
  template:
    src: upsmon.conf.j2
    dest: /etc/nut/upsmon.conf
    owner: nut
    group: nut
    mode: 0644
  notify:
  - restart nut daemon

- name: "get last scripts version"
  get_url:
    url: "{{item}}"
    dest: /usr/local/bin/{{item|basename}}
    owner: root
    group: root
    mode: 0755
  loop: 
    - https://raw.githubusercontent.com/belgotux/nutNotify/master/nutShutdown.sh
    - https://raw.githubusercontent.com/belgotux/nutNotify/master/nutNotify.sh
    - https://raw.githubusercontent.com/belgotux/nutNotify/master/nutNotifyBoot.sh
    - https://raw.githubusercontent.com/belgotux/nutNotify/master/nutNotifyFct.sh


- name: Copy nutNotify config file
  template:
    src: nutNotify.conf.j2
    dest: /usr/local/etc/nutNotify.conf
    owner: root
    group: root
    mode: 0644

- name: Create log folder
  file:
    path: "/var/log/nutNotify"
    owner: nut
    group: root
    mode: 0775
    state: directory

- name: Copy logrotate file
  get_url:
    url: https://raw.githubusercontent.com/belgotux/nutNotify/master/nutNotify.logrotate
    dest: /etc/logrotate.d/nutNotify
    owner: root
    group: root
    mode: 0644