- name: create systemd boot service
  get_url:
    url: "https://raw.githubusercontent.com/belgotux/nutNotify/master/systemd-notify"
    dest: /lib/systemd/system/nut-notify-boot.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd for nut-notify-boot

- name: replace default method
  lineinfile:
    dest: /lib/systemd/system/nut-notify-boot.service
    regexp: "^ExecStart"
    line: ExecStart=/usr/local/bin/nutNotifyBoot.sh {{notifynut_method_serveronline}}
  notify: reload systemd for nut-notify-boot
