- name: create systemd boot service
  get_url:
    url: "https://raw.githubusercontent.com/belgotux/nutNotify/master/systemd-notify"
    dest: /lib/systemd/system/nut-notify-boot.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd for nut-notify-boot

# - name: copy nutNotifyBoot.sh
#   copy:
#     src: nutNotify/nutNotifyBoot.sh
#     dest: /usr/local/bin/nutNotifyBoot.sh
#     owner: root
#     group: root
#     mode: 0755
- name: replace default notifynut_method
  lineinfile:
    dest: /lib/systemd/system/nut-notify-boot.service
    regexp: "^ExecStart"
    line: ExecStart=/usr/local/bin/nutNotifyBoot.sh {{notifynut_method}}
  notify: reload systemd for nut-notify-boot
- name: replace default notifynut_mailto for nut boot notification
  lineinfile:
    dest: /usr/local/bin/nutNotifyBoot.sh
    regexp: "^MAILTO"
    line: MAILTO={{notifynut_mailto}}
  notify: reload systemd for nut-notify-boot
    # this part always modify the script copy first... Need to fix