- name: restart nut daemon
  systemd:
    name: nut-monitor
    state: restarted
    daemon_reload: no
  retries: 5
  delay: 3
  register: result
  until: result.rc == 0
#  when: upsmon.changed == true